name: AS Cloud Telegram Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 310

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Bot
        run: timeout 18000 node bot.js || true
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
